name: Build and Deploy Docs

on:
  push:
    branches: [main]     # auto-deploy on push to main
  workflow_dispatch:     # manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20   # GitHub recommends >=20 now

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist   # VitePress build output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write         # needed for Pages deployment
      id-token: write      # needed for OIDC auth
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
